apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: demo-eureka-server
          image: beomsun22/eureka-server:v0.1
          ports:
            - containerPort: 8761
          imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: eureka-server
spec:
  ports:
    - port: 8761
      targetPort: 8761
  selector:
    app: eureka-server
  type: LoadBalancer