apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: beomsun22/gateway-service:v0.1
          ports:
            - containerPort: 8000
          imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: gateway-service
  type: LoadBalancer